<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>author</key>
    <string>jebbs, qjebbs@gmail.com</string>
    <key>comment</key>
    <string>All diagram and styles support.</string>
    <key>fileTypes</key>
    <array>
      <string>wsd</string>
      <string>iuml</string>
      <string>pu</string>
      <string>puml</string>
      <string>plantuml</string>
    </array>
    <key>name</key>
    <string>Diagram</string>
    <key>scopeName</key>
    <string>source.wsd</string>
    <key>uuid</key>
    <string>ca03e751-04ef-4330-9a6b-2199aae1c418</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>diagram block</string>
        <key>name</key>
        <string>diagram.source.wsd</string>
        <key>begin</key>
        <string>(?i)^\s*(@start(uml|salt))((\s+)(.+?))?\s*$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.diagram.source.wsd</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.diagram.source.wsd</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?i)^\s*(@end(uml|salt))\s*$</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.diagram.source.wsd</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#Comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Style</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Class</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Activity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Sequence</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#State</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#Gerneral</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>#Comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Style</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Class</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Object</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Activity</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Sequence</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#State</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#Gerneral</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>Comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>comment line</string>
            <key>name</key>
            <string>comment.line.comment.source.wsd</string>
            <key>begin</key>
            <string>(?i)^\s*(')</string>
            <key>end</key>
            <string>(?i)\n</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>comment block</string>
            <key>name</key>
            <string>comment.block.source.wsd</string>
            <key>begin</key>
            <string>(?i)^\s*(/')</string>
            <key>end</key>
            <string>(?i)^.*('/)</string>
          </dict>
        </array>
      </dict>
      <key>Style</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>inline style</string>
            <key>match</key>
            <string>(?i)^\s*(skinparam)\s+(\w+?)\s+((&lt;&lt;\s*.+?\s*&gt;&gt;)\s+)?([^\{\}]+?)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.skinparam.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.skinparam.keyword.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.skinparam.keyword.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.skinparam.value.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>style block</string>
            <key>begin</key>
            <string>(?i)^\s*((skinparam)(\s+(\w+?))?|(\w+)(\w*?)?)\s*\{\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.skinparam.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.other.skinparam.keyword.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.other.skinparam.keyword.source.wsd</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.other.skinparam.keyword.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*(?&lt;!\\)\}\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>inline style</string>
                <key>match</key>
                <string>(?i)^\s*(\w+?)\s+((&lt;&lt;\s*.+?\s*&gt;&gt;)\s+)?([^\{\}]+?)\s*$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.skinparam.keyword.source.wsd</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>constant.numeric.skinparam.keyword.source.wsd</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>string.quoted.double.skinparam.value.source.wsd</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>Keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>line begin keywords</string>
            <key>name</key>
            <string>keyword.other.linebegin.source.wsd</string>
            <key>match</key>
            <string>(?i)^\s*(usecase|actor|object|participant|boundary|control|entity|database|create|component|interface|package|node|folder|frame|cloud|annotation|enum|abstract|class|abstract\s+class|state|autonumber(\s+stop|resume)?|activate|deactivate|destroy|newpage|alt|else|opt|loop|par|break|critical|group|box|rectangle|namespace|partition)\b</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>whole line keywords</string>
            <key>name</key>
            <string>keyword.other.wholeline.source.wsd</string>
            <key>match</key>
            <string>(?i)^\s*(split( again)?|endif|repeat|start|stop|end|end\s+fork|end\s+split|fork( again)?|detach|end\s+box|top\s+to\s+bottom\s+direction|left\s+to\s+right\s+direction)\s*$</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>other keywords</string>
            <key>name</key>
            <string>keyword.other.other.source.wsd</string>
            <key>match</key>
            <string>(?i)\b(as|{(static|abstract)\})\b</string>
          </dict>
        </array>
      </dict>
      <key>Gerneral</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>multi-line title, enables ctrl+r jump list.</string>
            <key>begin</key>
            <string>(?i)^\s*(title)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.title.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?i)^\s*\b(end\s+title)\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.title.source.wsd</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(?i)^\s*(.+?)\s*$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.function.title.source.wsd</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>title, enables ctrl+r jump list.</string>
            <key>match</key>
            <string>(?i)^\s*(title)\s+(.+?)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.title.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.title.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>scale 1.5, scale 2/3, scale 200 width, scale 200 height, scale 200*100, scale max 300*200</string>
            <key>name</key>
            <string>keyword.other.scale.source.wsd</string>
            <key>match</key>
            <string>(?i)^\s*(scale)\s+((max)\s+)?(\d+(\.?\d+)?)\s*((([\*/])\s*(\d+\.?(\.?\d+)?))|(width|height))?\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.scale.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.scale.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.scale.source.wsd</string>
              </dict>
              <key>8</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.scale.source.wsd</string>
              </dict>
              <key>9</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.scale.source.wsd</string>
              </dict>
              <key>11</key>
              <dict>
                <key>name</key>
                <string>keyword.other.scale.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>inline note</string>
            <key>match</key>
            <string>(?i)^\s*(note\s(left|right))\s*:\s*(.+)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.note.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>comment.line.note.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>multiple note</string>
            <key>begin</key>
            <string>(?i)^\s*(note\s(left|right))\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.note.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?i)^\s*(end\s*note)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.note.source.wsd</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.multiple.note.source.wsd</string>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>inline note of over</string>
            <key>match</key>
            <string>(?i)^\s*([rh]?note)(?:\s+(right|left|top|bottom))?\s+(?:(?:(of|over)\s*(?:[^\s\w\d]([\w\s]+)[^\s\w\d]|(\w+)))|(on\s+link))\s*(#\w+)?\s*:\s*(.+)$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteof.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.noteof.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteof.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>support.variable.noteof.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>support.variable.noteof.source.wsd</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteof.source.wsd</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.noteof.source.wsd</string>
              </dict>
              <key>8</key>
              <dict>
                <key>name</key>
                <string>comment.line.noteof.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>multi-line note of over</string>
            <key>begin</key>
            <string>(?i)^\s*([rh]?note)(?:\s+(right|left|top|bottom))?\s+(?:(?:(of|over)\s*(?:[^\s\w\d]([\w\s]+)[^\s\w\d]|(\w+)))|(on\s+link))\s*(#\w+)?\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteof.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.noteof.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteof.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>support.variable.noteof.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>support.variable.noteof.source.wsd</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteof.source.wsd</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.noteof.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?i)^\s*(end\s*[rh]?note)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.multline.noteof.source.wsd</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.multline.noteof.source.wsd</string>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>float note, note as</string>
            <key>match</key>
            <string>(?i)^\s*(note)\s+(".+?")\s+(as)\s+([\w\d]+)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteas.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.noteas.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.noteas.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>support.variable.noteas.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>multi-line header, legend, footer</string>
            <key>begin</key>
            <string>(?i)^\s*(header|legend|footer)\s*\n</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.header_legend_footer.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?i)^\s*(end\s?(header|legend|footer))</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.header_legend_footer.source.wsd</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.header_legend_footer.source.wsd</string>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>header, legend, footer</string>
            <key>match</key>
            <string>(?i)^\s*(header|legend|footer)\s+(.+?)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.title.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.header_legend_footer.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>Preprocessings</string>
            <key>name</key>
            <string>support.class.preprocessings.source.wsd</string>
            <key>match</key>
            <string>(?i)(!include|!enddefinelong|!definelong|!define|!ifdef|!else|!endif)</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>links</string>
            <key>begin</key>
            <string>(?i)((?:(?:(?:\s+[ox]|[+*])?(?:&lt;\|?|&lt;&lt;|\\\\|\\|//|\})?)(?=[-.]))[-.]+(\[(?:\#(?:[0-9a-f]{6}|[0-9a-f]{3}|\w+)(?:[-\\/](?:[0-9a-f]{6}|[0-9a-f]{3}|\w+))?\b)\])?(?:(left|right|up|down)(?:[-.]))?[-.]*(?:(?:\|?&gt;|&gt;&gt;|\\\\|\\|//|\{)?(?:[ox]\s+|[+*])?))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.note.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.link.color.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.language.link.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#Gerneral</string>
              </dict>
              <dict>
                <key>comment</key>
                <string>actor and link message</string>
                <key>match</key>
                <string>(?i):([^:]+):\s*:(.+)$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>support.variable.actor.link.source.wsd</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>comment.line.message.link.source.wsd</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>link message</string>
                <key>match</key>
                <string>(?i):(.+)$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>comment.line.message.link.source.wsd</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>all color names</string>
            <key>match</key>
            <string>(?i)#(?:[0-9a-f]{6}|[0-9a-f]{3}|\w+)</string>
            <key>name</key>
            <string>constant.numeric.colors.source.wsd</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>double quoted</string>
            <key>name</key>
            <string>string.quoted.double.source.wsd</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>single quoted</string>
            <key>name</key>
            <string>string.quoted.single.source.wsd</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>Variables</string>
            <key>name</key>
            <string>support.variable.source.wsd</string>
            <key>match</key>
            <string>\b[\w_]+</string>
          </dict>
        </array>
      </dict>
      <key>Activity</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>if</string>
            <key>match</key>
            <string>(?i)^\s*(else *if|if)\s?\((.+?)\)\s?(then)(\s?\((.+?)\))?\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.if.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.activity.if.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.if.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>comment.line.activity.if.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>else</string>
            <key>match</key>
            <string>(?i)^\s*(else)(\s?\((.+?)\))?\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.else.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>comment.line.activity.else.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>while is, repeat while is</string>
            <key>match</key>
            <string>(?i)^\s*(repeat\s+)?(while)\s*\((.+?)\)(\s*(is)(\s*\((.+?)\))?)?\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.while.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.while.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.activity.while.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.while.source.wsd</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>comment.line.activity.while.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>endwhile</string>
            <key>match</key>
            <string>(?i)^\s*(end)\s?(while)(\s*\((.+?)\))?\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.endwhile.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.activity.endwhile.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>comment.line.activity.endwhile.source.wsd</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>Sequence</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>divider</string>
            <key>match</key>
            <string>(?i)^\s*(={2,})\s*(.+?)\s*(={2,})\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.divider.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.sequence.divider.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.divider.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>...</string>
            <key>match</key>
            <string>(?i)^\s*(\.{3,})\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.omission.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>inline ref</string>
            <key>match</key>
            <string>(?i)^\s*(ref\s+over)\s+(.+?)\s*:\s*(.+)\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.sequence.ref.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.variable.sequence.ref.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>comment.line.sequence.ref.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>multi-line ref</string>
            <key>begin</key>
            <string>(?i)^\s*(ref\s+over)\s+(.+?)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.sequence.ref.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.variable.sequence.ref.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?i)end\s+ref</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.other.sequence.ref.source.wsd</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.line.sequence.ref.source.wsd</string>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>delay</string>
            <key>match</key>
            <string>(?i)^\s*(\.{3,})\s*(.+)\s*(\.{3,})\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.delay.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.sequence.delay.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.delay.source.wsd</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>space</string>
            <key>match</key>
            <string>(?i)(\|{2,})(\d+)?(\|{1,})</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.space.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.sequence.space.source.wsd</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.sequence.space.source.wsd</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>State</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>concurrent</string>
            <key>match</key>
            <string>(?i)^\s*(-{2,})\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.state.concurrent.source.wsd</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>Object</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>add object fileds</string>
            <key>match</key>
            <string>(?i)^\s*([\w\d_]+)\s+:\s+s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.variable.object.addfileds.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>comment.line.object.addfileds.source.wsd</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>Class</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>class group &amp; enum</string>
            <key>begin</key>
            <string>(?i)^\s*(enum|abstract|class|abstract\s+class)\s+([\w\d_\.]+|"[^"]+")(\s*(&lt;&lt;.+?&gt;&gt;))?(\s+(as)\s+([\w\d_\.]+|"[^"]+")(\s*(&lt;&lt;.+?&gt;&gt;))?)?(\s+#(([\w\|\\\/\-]+)))?\s*\{\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.class.group.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.variable.class.group.source.wsd</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.class.definition.source.wsd</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>keyword.other.class.group.source.wsd</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>support.variable.class.group.source.wsd</string>
              </dict>
              <key>9</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.class.definition.source.wsd</string>
              </dict>
              <key>10</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.class.definition.source.wsd</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*(?&lt;!\\)\}\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>body separator</string>
                <key>match</key>
                <string>(?i)^\s*([.=_-]{2,})\s*((.+?)\s*([.=_-]{2,}))?</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>comment.line.class.group.separator.source.wsd</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>string.quoted.double.class.group.separator.source.wsd</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>comment.line.class.group.separator.source.wsd</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>function</string>
                <key>match</key>
                <string>(?i)^\s*(\s*\{(static|abstract)\}\s*)?(\s*[~#+-]\s*)?((\w+(\[\])?)\s+)?([0-9a-zA-Z_]+)(\(\))\s*$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.class.fileds.source.wsd</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.class.fileds.source.wsd</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.class.function.source.wsd</string>
                  </dict>
                  <key>7</key>
                  <dict>
                    <key>name</key>
                    <string>support.variable.class.function.source.wsd</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>fields</string>
                <key>match</key>
                <string>(?i)^\s*(\s*\{(static|abstract)\}\s*)?(\s*[~#+-]\s*)?((\w+(\[\])?)\s+([0-9a-zA-Z_]+)|([0-9a-zA-Z_]+)\s*:\s*(\w+))\s*$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.class.fileds.source.wsd</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.class.fileds.source.wsd</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.class.fileds.source.wsd</string>
                  </dict>
                  <key>7</key>
                  <dict>
                    <key>name</key>
                    <string>support.variable.class.fileds.source.wsd</string>
                  </dict>
                  <key>8</key>
                  <dict>
                    <key>name</key>
                    <string>support.variable.class.fileds.source.wsd</string>
                  </dict>
                  <key>9</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.class.fileds.source.wsd</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>comment</key>
                <string>other fileds/function</string>
                <key>match</key>
                <string>(?i)^\s*(\s*\{(static|abstract)\}\s*)?(\s*[~#+-]\s*)?(.+?)\s*$</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>storage.modifier.class.fileds.source.wsd</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.class.fileds.source.wsd</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>string.quoted.double.class.other.source.wsd</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>comment</key>
            <string>hide &amp; show</string>
            <key>match</key>
            <string>(?i)^\s*(hide|show)\s+(([\w\d_\.]+|"[^"]+")|&lt;&lt;.+?&gt;&gt;|Stereotypes|class|interface|enum)(\s+(empty fields|empty methods|fields|attributes|methods|members|circle))?\s*$</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.class.hideshow.source.wsd</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.variable.class.hideshow.source.wsd</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.class.hideshow.source.wsd</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>